{{- if .Values.global.clusterScopedResources }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "k8ssandra-common.fullname" . }}-serving-cert
    {{- with include "k8ssandra-common.annotations" . }}
      {{- . | nindent 4 }}
    {{- end }}
  labels: {{ include "k8ssandra-common.labels" . | indent 4 }}
  name: {{ include "k8ssandra-common.fullname" . }}-mutating-webhook-configuration
webhooks:
{{- if .Values.controlPlane }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "k8ssandra-common.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-k8ssandra-io-v1alpha1-k8ssandracluster
  failurePolicy: Fail
  name: mk8ssandracluster.kb.io
  rules:
  - apiGroups:
    - k8ssandra.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - k8ssandraclusters
  sideEffects: None
{{- end }}
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "k8ssandra-common.fullname" . }}-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1-pod-secrets-inject
  failurePolicy: Fail
  name: mpod.kb.io
  objectSelector:
    matchLabels:
      app.kubernetes.io/created-by: cass-operator
    matchExpressions:
    - key: control-plane
      operator: NotIn
      values:
      - k8ssandra-operator
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None
{{- end }}
